services:
  - type: web
    name: openai-phoenix-web
    env: docker
    plan: free
    buildCommand: ./render-build.sh
    startCommand: _build/prod/rel/openai_phoenix/bin/openai_phoenix start
    autoDeploy: true
    envVars:
      - key: MIX_ENV
        value: "prod"
      - key: PHX_SERVER
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: openai-phoenix-db
          property: connectionString
      - key: PORT
        value: "4000"
      - key: POOL_SIZE
        value: "10"

databases:
  - name: openai-phoenix-db
    plan: free
